routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/blog/category/{slug?}', 'BlogController@category' )->name('category');
Route::get('/blog/article/{slug?}', 'BlogController@article' )->name('article');

/*Route::get('/blog/category/{slug?}', function ($slug) {
    echo '$slug';
});*/

Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']],function(){
  Route::get('/', 'DashboardController@dashboard')->name('admin.index');
  Route::resource('/category', 'CategoryController', ['as'=>'admin']);
  Route::resource('/article', 'ArticleController', ['as'=>'admin']);
  Route::group(['prefix'=>'user_managment', 'namespace'=>'UserManagment'],function(){
    Route::resource('/user', 'UserController', ['as'=>'admin.user_managment']);
  });
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UserManagment/UserController.php
<?php

namespace App\Http\Controllers\Admin\UserManagment;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user_managment.users.index',[
          'users'=> User::paginate(20)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user_managment.users.create', [
            'user' => []
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $validator = $request->validate([
          'name' => 'required|string|max:255',
          'email' => 'required|string|email|max:255|unique:users',
          'password' => 'required|string|min:6|confirmed',
      ]);

        User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => bcrypt($request['password']),
        ]);
        return redirect()->route('admin.user_managment.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.user_managment.users.edit',[
          'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
      $validator = $request->validate([
          'name' => 'required|string|max:255',
          'email' => [
            'required',
            'string',
            'email',
            'max:255',
            \Illuminate\Validation\Rule::unique('users')->ignore($user->id)
            ],
          'password' => 'nullable|string|min:6|confirmed',
      ]);
        $user->name = $request['name'];
        $user->email = $request['email'];
        $request['password'] == null ? : $user->password = bcrypt($request['password']);
        $user->save();

        return redirect()->route('admin.user_managment.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
       $user->delete();
       return redirect()->route('admin.user_managment.user.index');
    }
}

resources/views/admin/user_managment/users/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">

    @component('admin.components.breadcrumb')
      @slot('title') Создание пользователя @endslot
      @slot('parent') Главная @endslot
      @slot('active') Пользователь @endslot
    @endcomponent
        <hr />
        <form class="from-horozontal" action="{{route('admin.user_managment.user.store')}}" method="post">
          {{ csrf_field() }}

          <!-- Form include -->
          @include('admin.user_managment.users.partials.form')
        </form>

  </div>

@endsection

resources/views/admin/user_managment/users/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">

    @component('admin.components.breadcrumb')
      @slot('title') Редактирование пользователя @endslot
      @slot('parent') Главная @endslot
      @slot('active') Пользователь @endslot
    @endcomponent
        <hr />
        <form class="from-horozontal" action="{{route('admin.user_managment.user.update', $user)}}" method="post">
          {{ method_field('PUT')}}
          {{ csrf_field() }}

          <!-- Form include -->
          @include('admin.user_managment.users.partials.form')
        </form>

  </div>

@endsection

resources/views/admin/user_managment/users/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  @component('admin.components.breadcrumb')
    @slot('title') Список пользователей @endslot
    @slot('parent') Главная @endslot
    @slot('active') Пользователи @endslot
  @endcomponent

  <hr>

  <a href="{{route('admin.user_managment.user.create')}}" class="btn btn-primary pull-right"><i class="fa fa-plus-square-o"></i> Создать пользователя</a>

  <table class="table table-striped">
    <thead>
      <th>Имя</th>
      <th>E-mail</th>
      <th class="text-right">Действие</th>
    </thead>
    <tbody>
      @forelse ($users as $user)
        <tr>
          <td>{{$user->name}}</td>
          <td>{{$user->email}}</td>
          <td class="text-right">
            <form onsubmit="if(confirm('Удалить?')){ return true }else{ return false }" action="{{route('admin.user_managment.user.destroy', $user)}}" method="post">
              {{method_field('DELETE')}}
              {{ csrf_field() }}
              <a class="btn btn-default" href="{{route('admin.user_managment.user.edit',$user)}}"> <i class="fa fa-edit"></i></a>
              <button type="submit"  class="btn" > <i class="fa fa-trash-o"></i> </button>
            </form>
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="3" class="text-center"> <h2>Данные отсутствуют</h2> </td>
        </tr>
      @endforelse
      <tfoot>
        <tr>
          <td colspan="3">
            <ul class="pagination pull-right">
              {{$users->links()}}
            </ul>
          </td>
        </tr>
      </tfoot>
    </tbody>
  </table>
@endsection