routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/blog/category/{slug?}', 'BlogController@category' )->name('category');
Route::get('/blog/article/{slug?}', 'BlogController@article' )->name('article');

/*Route::get('/blog/category/{slug?}', function ($slug) {
    echo '$slug';
});*/

Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']],function(){
  Route::get('/', 'DashboardController@dashboard')->name('admin.index');
  Route::resource('/category', 'CategoryController', ['as'=>'admin']);
  Route::resource('/article', 'ArticleController', ['as'=>'admin']);
  Route::group(['prefix'=>'user_managment', 'namespace'=>'UserManagment'],function(){
    Route::resource('/user', 'UserController', ['as'=>'admin.user_managment']);
  });
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Support\Str;



class Article extends Model
{
  //mass assigned
  protected $fillable = ['title', 'slug', 'description_short', 'description', 'image', 'image_show', 'meta_title', 'meta_description', 'meta_keyword', 'published', 'created_by', 'modified_by'];

  //Mutators
    public function setSlugAttribute($value) {
      $this->attributes['slug'] = Str::slug( mb_substr($this->title, 0, 40) .  "-" . \Carbon\Carbon::now()->format('dmyHi'), '-');
    }

    //polymorphic relation with categories
    public function categories()
    {
      return $this->morphToMany('App\Category', 'categoryable');
    }

    public function scopeLustArticles($query, $count) {
      return $query->orderBy('created_at', 'desc')->take($count)->get();
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.articles.index', [
          'articles' => Article::orderBy('created_at', 'desc')->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() // data for show create form
    {
        return view('admin.articles.create', [

          'article'    => [],
          'categories' => Category::with('children')->where('parent_id', 0)->get(),
          'delimiter'  => ''

        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) // write article data to table articles
    {
        $article = Article::create($request->all());
        //categories
        if ($request->input('categories')) :
          $article->categories()->attach($request->input('categories'));
        endif;

        return redirect()->route('admin.article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
      return view('admin.articles.edit', [

        'article'    => $article,
        'categories' => Category::with('children')->where('parent_id', 0)->get(),
        'delimiter'  => ''

      ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $article->update($request->except('slug'));

        $article->categories()->detach();
        if ($request->input('categories')) :
          $article->categories()->attach($request->input('categories'));
        endif;

        return redirect()->route('admin.article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
      $article->categories()->detach();
      $article->delete();
      return redirect()->route('admin.article.index');
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">

    @component('admin.components.breadcrumb')
      @slot('title') Создание новости @endslot
      @slot('parent') Главная @endslot
      @slot('active') Новости @endslot
    @endcomponent



        <hr />

        <form class="from-horozontal" action="{{route('admin.article.store')}}" method="post">
          {{ csrf_field() }}

          <!-- Form include -->
          @include('admin.articles.partials.form')

          <input type="hidden" name="created_by" value="{{Auth::id()}}">
        </form>

  </div>

@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">

    @component('admin.components.breadcrumb')
      @slot('title') Редактирование новости @endslot
      @slot('parent') Главная @endslot
      @slot('active') Новости @endslot
    @endcomponent



        <hr />

        <form class="from-horozontal" action="{{route('admin.article.update', $article)}}" method="post">
          <input type="hidden" name="_method" value="put">
          {{ csrf_field() }}

          <!-- Form include -->
          @include('admin.articles.partials.form')

          <input type="hidden" name="modified_by" value="{{Auth::id()}}">
        </form>

  </div>

@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  @component('admin.components.breadcrumb')
    @slot('title') Список новостей @endslot
    @slot('parent') Главная @endslot
    @slot('active') Новости @endslot
  @endcomponent

  <hr>

  <a href="{{route('admin.article.create')}}" class="btn btn-primary pull-right"><i class="fa fa-plus-square-o"></i> Создать новость</a>

  <table class="table table-striped">
    <thead>
      <th>Наименование</th>
      <th>Публикация</th>
      <th class="text-right">Действие</th>
    </thead>
    <tbody>
      @forelse ($articles as $article)
        <tr>
          <td>{{$article->title}}</td>
          <td>{{$article->published}}</td>
          <td class="text-right">
            <form onsubmit="if(confirm('Удалить?')){ return true }else{ return false }" action="{{route('admin.article.destroy', $article)}}" method="post">
              <input type="hidden" name="_method" value="DELETE">
              {{ csrf_field() }}
              <a class="btn btn-default" href="{{route('admin.article.edit',$article)}}"> <i class="fa fa-edit"></i></a>
              <button type="submit"  class="btn" > <i class="fa fa-trash-o"></i> </button>
            </form>
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="3" class="text-center"> <h2>Данные отсутствуют</h2> </td>
        </tr>
      @endforelse
      <tfoot>
        <tr>
          <td colspan="3">
            <ul class="pagination pull-right">
              {{$articles->links()}}
            </ul>
          </td>
        </tr>
      </tfoot>
    </tbody>
  </table>
@endsection